name: dis_logger
description: "A Flutter package that helps you send logs to Discord server channels with easy and simple setup."
version: 0.0.1
# homepage: https://github.com/1far4z1/dis_logger/tree/main
repository: https://github.com/1farz1/dis_logger/true/main
issue_tracker: https://github.com/1farz1/dis_logger/issues
documentation: https://github.com/1farz1/dis_logger/blob/main/README.md

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  logger: ^2.5.0
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


topics:
  - logging
  - flutter
  - discord
  - debugging
  - error-reporting
  - tracking
  - analytics

flutter:
  # This section is optional since this is a plugin package
  # You can add assets if needed
  # assets:
  #   - assets/images/
